enum TypeEnum {
  NORMAL = 'normal',
  FIRE = 'fire',
  WATER = 'water',
  ELECTRIC = 'electric',
  GRASS = 'grass',
  ICE = 'ice',
  FIGHTING = 'fighting',
  POISON = 'poison',
  GROUND = 'ground',
  FLYING = 'flying',
  PSYCHIC = 'psychic',
  BUG = 'bug',
  ROCK = 'rock',
  GHOST = 'ghost',
  DRAGON = 'dragon',
  DARK = 'dark',
  STEEL = 'steel',
  FAIRY = 'fairy',
  UNKNOWN = 'unknown',
  SHADOW = 'shadow',
}

enum TypeColorEnum {
  NORMAL = '#A8A77A',
  FIRE = '#EE8130',
  WATER = '#6390F0',
  ELECTRIC = '#F7D02C',
  GRASS = '#7AC74C',
  ICE = '#96D9D6',
  FIGHTING = '#C22E28',
  POISON = '#A33EA1',
  GROUND = '#E2BF65',
  FLYING = '#A98FF3',
  PSYCHIC = '#F95587',
  BUG = '#A6B91A',
  ROCK = '#B6A136',
  GHOST = '#735797',
  DRAGON = '#6F35FC',
  DARK = '#705746',
  STEEL = '#B7B7CE',
  FAIRY = '#D685AD',
  UNKNOWN = '#777',
  SHADOW = '#777',
}

export { TypeEnum, TypeColorEnum };
